### ISSUE TITLE
[Bug]: 0.5.2.1 won't launch

### ISSUE THREAD

**Issue by incanus** [OmniNull/OmniWM#443]
### Issue type

Crash

### What happened? (actual behavior)

Not sure if this is a Sequoia-specific issue, but the app won't launch. Trying at CLI yields: 

```bash
$ /Applications/OmniWM.app/Contents/MacOS/OmniWM
OmniWM/SkyLight.swift:189: Fatal error: SkyLight missing required symbol: SLSWindowIteratorGetCornerRadii
```

### What did you expect?

App to launch. 

### Reproduction steps

Launch the app. 

### OmniWM version

v0.5.2.1

### macOS version

15.7.5

### Active layout

Not sure / both

### Did this work in an earlier version?

works in v0.5.2

### Before submitting

- [x] I searched existing open and closed issues and confirmed this isn't a duplicate.
- [x] I'm on a recent OmniWM version and the issue still occurs.

**Comment by BarutSRB** [comment]
That is definitely a sequoi missing a skylight api that is available in macOS 26+ I did start to modernize the api as im using macOS 27 beta and pretty much I think when it is released no one will stay on 26 as 27 beta is already miles better. As for Seqouia once macOS 27 comes out I'll have to re-think about supporting it. I'll have to see from previous version which fallback api it was using and re-add it

**Comment by BarutSRB** [comment]
Sorry after second thought Sequoia won't be supported, and macOS 26 will stop beign supported once macOS 27 is released.

**Comment by incanus** [comment]
That's a pretty abrupt and bitter pill for a `x.x.x.y` release. ☹️

**Comment by BarutSRB** [comment]
I know and Im sorry but working night shifts and lacking time to properly keep building is getting hard especially since I have to make sure everything works for macos 27 which is going to release probably in about 2 months... And I truly don't want to vibe code as this isn't a type of program that should be vibe coded if it was an mvp or hobby website ok. Maybe later when I have more time or finish what I have in mind I might revisit this decision or if a proper contributor jumps in to help.

**Comment by incanus** [comment]
I appreciate the work you put in. I'd be better situated to help if I was running the new OS's, which is a Catch-22. 😆 I'll stay tuned. Fortunately v0.5.2 is stable for me and doesn't really have any quirks that are dealbreakers for the time being.
